sudo: require
dist: xenial
language: bash

notifications:
  email: false

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y texlive-base texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra texlive-lang-spanish

script:
  - bash ./travisTest.sh ./ Documentacion
